### ISSUE TITLE
Custom Emoticons

### ISSUE THREAD

**Issue by SimonMeskens** [dogancelik/irccloud-twitch-emoticons#1]
Can we have a way to add custom emoticons?

I'd like to have smileys, like :) this, convert to either emoji or the IRCCloud emoji image replacements, but only on my end (I know I can already change it to send emoji by using Send With Style). Preferably, I'd like to manage this list myself.

Something like Send with Style, where I can enter a list of mappings would probably be perfect, so I can do something like this:

:-),: smiley:
;-),Kappa

This would change both what I type and what others type into the correct emoticon, but only on my end. Support for IRCCloud image replacements would be good, since I'm using Chrome.

**Comment by SimonMeskens** [comment]
The image replacements with proper naming are here btw: https://github.com/irccloud/emoji-cheat-sheet.com/tree/master/public/graphics/emojis

**Comment by dogancelik** [comment]
Do you have any particular emoticon / image set in your mind? 

**e.g. MSN emoticons**

![MSN emoticons](http://addons.miranda-ng.org/upload/images/3713_64-1-1209011561-msnemoticons.png)

**Comment by SimonMeskens** [comment]
Sure, so here are the replacements I currently run:
![replacements](http://i.imgur.com/XLTNqKU.png)

All of the images are available here:
https://github.com/WebpageFX/emoji-cheat-sheet.com/tree/master/public/graphics/emojis

**Comment by dogancelik** [comment]
So if I understand you right,
you want to use these characters: `<3`, `</3`, `8)`, `D:`)
and turn them to: :heart:, :broken_heart:, :sunglasses:, :anguished:
You can already do this in SWS
![animation](https://cloud.githubusercontent.com/assets/486818/17417783/cadf4fb2-5a9d-11e6-8359-e7e666da9424.gif)

SWS is enabled on Firefox, and disabled on Chrome

If you want ALL emojis as shortcuts like `<3` or `:-)`, that's not possible because I'm not sure you can use turn :car: emoji into `(o_o)/////(o_o)`

**Comment by SimonMeskens** [comment]
The problem with using SWS is that it will change it for not just me, but for everyone. Most of the people I chat with don't have emoji support yet, so I just want to change it on my screen, like the twitch emoticons in this plugin. Does that make sense? The only ones I want to change are the ones in the image above (text to image, not the other way round).

**Comment by dogancelik** [comment]
So you want to see :heart:, and others to see `<3`.
I'm a little busy right now but I can do this next week.
I want to add this set as a emoticon pack so other people can enjoy too.
If the code doesn't get big or complicated, I'll allow users to create their own emoticons. So people can make theirs and/or share :smiley:
Thanks for the suggestion :+1:

**Comment by SimonMeskens** [comment]
No problem, thanks for investing time in it, my own solution is very hacky :smile: 

BTW, the Github I linked with images are the ones used by IRCCloud and a ton of other services, so they are good images to use.

Here's the json I use: 
http://pastebin.com/raw/6BCjVNkK

And this is the html I use to render them:
`var templateSmileys = '<span title=":name" style="background-image:url(https://raw.githubusercontent.com/WebpageFX/emoji-cheat-sheet.com/master/public/graphics/emojis/:src.png)" class="emoji emoji-sizer">:name</span>';`

**Comment by SimonMeskens** [comment]
I also had to edit this function to make the regex work correctly. From testing done so far, this seems to work just fine (\b doesn't work because these aren't words):

```
function getWordRegex(key, opts) {
  if (typeof opts === 'undefined') {
    opts = 'g';
  }
  var t = new RegExp('(\\S)?' + escapeRegExp(key) + '(?!\\S)', opts);
  return t;
}
```

The problem is that this seems to break the twitch emoticons

**Comment by dogancelik** [comment]
Don't worry, I'll take care all of these :)

**Comment by SimonMeskens** [comment]
Yeah, just wanted to give you the result of my experiments, so you didn't have to do double work :smile: 

I'm quite sure you'll do a better job or I wouldn't suggest it here :wink:

**Comment by dogancelik** [comment]
Hey Simon, I have been busy so I didn't have chance to push the changes, here's a early preview:
Currently, it only supports online URLs, so you can't use local files.
Still you can use a private Gist URL to use custom emoticon packs.
[irccloud-emoticons.user.js](https://github.com/dogancelik/irccloud-emoticons/raw/dev/build/irccloud-emoticons.user.js)

Don't forget to check [irccloud-ext/emoticon-packs](https://github.com/irccloud-ext/emoticon-packs) for additional emoticon packs.

I'll try to be on IRCCloud IRC network under name `Dogan` so if you find me, we can work on this together.

**Comment by SimonMeskens** [comment]
Thanks for the hard work! You're the champ. I'll play around with it a bit and try to find you on IRC :+1:

**Comment by dogancelik** [comment]
Here's MSN emoticon pack, you can look at [source code here](https://github.com/irccloud-ext/emoticon-packs/blob/gh-pages/msn/msn.json)

![msn](https://cloud.githubusercontent.com/assets/486818/18023165/885bcdce-6bfe-11e6-9a6e-24a438b8c18f.png)

You need to add `/msn/msn` to Active Packs to enable MSN pack like below

![sets](https://cloud.githubusercontent.com/assets/486818/18023190/c425aa14-6bfe-11e6-8236-98171ffe67e7.png)

**Comment by dogancelik** [comment]
![simon](https://cloud.githubusercontent.com/assets/486818/18024504/83142242-6c14-11e6-95c8-40337d99691f.gif)
(ignore discoloration on GIF)

I published your set as a custom pack so you can use this URL `/simon` in Settings

![simon2](https://cloud.githubusercontent.com/assets/486818/18024509/b3118a2a-6c14-11e6-82fb-f9b33487a9d9.png)

**Comment by SimonMeskens** [comment]
Seems to work awesomely here! Great job!

**Comment by dogancelik** [comment]
Then we can close this 😄
