### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by Smile4ever** [dogancelik/irccloud-twitch-emoticons#2]
I cannot get it to work. Is it supposed to replace :) automatically by an emoticon? Where do I configure it?

**Comment by dogancelik** [comment]
Hello @Smile4ever, this is an Tampermonkey extension that allows IRCCloud users to use emoticons from Twitch.tv (a streaming platform for gamers). If  you want to use it, you need to install Tampermonkey first.

In the screenshot below, when you type and press enter:
![Kappa1](https://user-images.githubusercontent.com/486818/64081042-5a4bef80-cd04-11e9-9dc6-7d49b7303cea.png)

It will convert `Kappa` to that emoticon:
![Kappa2](https://user-images.githubusercontent.com/486818/64081041-59b35900-cd04-11e9-99ac-620b98eba56a.png)

To see all available Twitch emoticons, please see: [twitchemotes.com](https://twitchemotes.com/)

**Comment by Smile4ever** [comment]
I got it to work with your explanation. Still, I was expecting :) to be replaced by a happy face.

How do I enable the custom emoticon pack "msn"? Typing /msn in an IRC channel results into
![image](https://user-images.githubusercontent.com/544411/64081285-07bc0480-ccff-11e9-9a7b-01dee111571e.png)

Looking forward to your answer.

**Comment by dogancelik** [comment]
![Settings1](https://user-images.githubusercontent.com/486818/64081314-dbf14c80-cd07-11e9-95bd-87fe5a0b2c41.png)

1. Click Account settings & info
2. Click Settings

![Settings2](https://user-images.githubusercontent.com/486818/64081318-f0354980-cd07-11e9-9b32-084c7391da6e.png)

3. Click "Emoticons" on menu
4. Add `/msn` to Active Packs.
5. Click Done and refresh page.

Also I updated the script (the menu link was not appearing). You need to re-install the new version (3.0.8): [click here to install](https://github.com/dogancelik/irccloud-emoticons/raw/master/build/irccloud-emoticons.user.js)

It should work after that :)

![image](https://user-images.githubusercontent.com/486818/64081407-14ddf100-cd09-11e9-9839-ad086b14d729.png)

**Comment by Smile4ever** [comment]
I was able to get it working with your detailed explanation.

I should probably create a custom emoticon pack with the emoticons from Telegram for my use case. Thank you.
